package stdlib

import (
	"math"

	"github.com/d5/tengo"
)

var mathModule = map[string]tengo.Object{
	"e":         &tengo.Float{Value: math.E},
	"pi":        &tengo.Float{Value: math.Pi},
	"phi":       &tengo.Float{Value: math.Phi},
	"sqrt2":     &tengo.Float{Value: math.Sqrt2},
	"sqrtE":     &tengo.Float{Value: math.SqrtE},
	"sqrtPi":    &tengo.Float{Value: math.SqrtPi},
	"sqrtPhi":   &tengo.Float{Value: math.SqrtPhi},
	"ln2":       &tengo.Float{Value: math.Ln2},
	"log2E":     &tengo.Float{Value: math.Log2E},
	"ln10":      &tengo.Float{Value: math.Ln10},
	"log10E":    &tengo.Float{Value: math.Log10E},
	"abs":       &tengo.GoFunction{Name: "abs", Value: FuncAFRF(math.Abs)},
	"acos":      &tengo.GoFunction{Name: "acos", Value: FuncAFRF(math.Acos)},
	"acosh":     &tengo.GoFunction{Name: "acosh", Value: FuncAFRF(math.Acosh)},
	"asin":      &tengo.GoFunction{Name: "asin", Value: FuncAFRF(math.Asin)},
	"asinh":     &tengo.GoFunction{Name: "asinh", Value: FuncAFRF(math.Asinh)},
	"atan":      &tengo.GoFunction{Name: "atan", Value: FuncAFRF(math.Atan)},
	"atan2":     &tengo.GoFunction{Name: "atan2", Value: FuncAFFRF(math.Atan2)},
	"atanh":     &tengo.GoFunction{Name: "atanh", Value: FuncAFRF(math.Atanh)},
	"cbrt":      &tengo.GoFunction{Name: "cbrt", Value: FuncAFRF(math.Cbrt)},
	"ceil":      &tengo.GoFunction{Name: "ceil", Value: FuncAFRF(math.Ceil)},
	"copysign":  &tengo.GoFunction{Name: "copysign", Value: FuncAFFRF(math.Copysign)},
	"cos":       &tengo.GoFunction{Name: "cos", Value: FuncAFRF(math.Cos)},
	"cosh":      &tengo.GoFunction{Name: "cosh", Value: FuncAFRF(math.Cosh)},
	"dim":       &tengo.GoFunction{Name: "dim", Value: FuncAFFRF(math.Dim)},
	"erf":       &tengo.GoFunction{Name: "erf", Value: FuncAFRF(math.Erf)},
	"erfc":      &tengo.GoFunction{Name: "erfc", Value: FuncAFRF(math.Erfc)},
	"exp":       &tengo.GoFunction{Name: "exp", Value: FuncAFRF(math.Exp)},
	"exp2":      &tengo.GoFunction{Name: "exp2", Value: FuncAFRF(math.Exp2)},
	"expm1":     &tengo.GoFunction{Name: "expm1", Value: FuncAFRF(math.Expm1)},
	"floor":     &tengo.GoFunction{Name: "floor", Value: FuncAFRF(math.Floor)},
	"gamma":     &tengo.GoFunction{Name: "gamma", Value: FuncAFRF(math.Gamma)},
	"hypot":     &tengo.GoFunction{Name: "hypot", Value: FuncAFFRF(math.Hypot)},
	"ilogb":     &tengo.GoFunction{Name: "ilogb", Value: FuncAFRI(math.Ilogb)},
	"inf":       &tengo.GoFunction{Name: "inf", Value: FuncAIRF(math.Inf)},
	"is_inf":    &tengo.GoFunction{Name: "is_inf", Value: FuncAFIRB(math.IsInf)},
	"is_nan":    &tengo.GoFunction{Name: "is_nan", Value: FuncAFRB(math.IsNaN)},
	"j0":        &tengo.GoFunction{Name: "j0", Value: FuncAFRF(math.J0)},
	"j1":        &tengo.GoFunction{Name: "j1", Value: FuncAFRF(math.J1)},
	"jn":        &tengo.GoFunction{Name: "jn", Value: FuncAIFRF(math.Jn)},
	"ldexp":     &tengo.GoFunction{Name: "ldexp", Value: FuncAFIRF(math.Ldexp)},
	"log":       &tengo.GoFunction{Name: "log", Value: FuncAFRF(math.Log)},
	"log10":     &tengo.GoFunction{Name: "log10", Value: FuncAFRF(math.Log10)},
	"log1p":     &tengo.GoFunction{Name: "log1p", Value: FuncAFRF(math.Log1p)},
	"log2":      &tengo.GoFunction{Name: "log2", Value: FuncAFRF(math.Log2)},
	"logb":      &tengo.GoFunction{Name: "logb", Value: FuncAFRF(math.Logb)},
	"max":       &tengo.GoFunction{Name: "max", Value: FuncAFFRF(math.Max)},
	"min":       &tengo.GoFunction{Name: "min", Value: FuncAFFRF(math.Min)},
	"mod":       &tengo.GoFunction{Name: "mod", Value: FuncAFFRF(math.Mod)},
	"nan":       &tengo.GoFunction{Name: "nan", Value: FuncARF(math.NaN)},
	"nextafter": &tengo.GoFunction{Name: "nextafter", Value: FuncAFFRF(math.Nextafter)},
	"pow":       &tengo.GoFunction{Name: "pow", Value: FuncAFFRF(math.Pow)},
	"pow10":     &tengo.GoFunction{Name: "pow10", Value: FuncAIRF(math.Pow10)},
	"remainder": &tengo.GoFunction{Name: "remainder", Value: FuncAFFRF(math.Remainder)},
	"signbit":   &tengo.GoFunction{Name: "signbit", Value: FuncAFRB(math.Signbit)},
	"sin":       &tengo.GoFunction{Name: "sin", Value: FuncAFRF(math.Sin)},
	"sinh":      &tengo.GoFunction{Name: "sinh", Value: FuncAFRF(math.Sinh)},
	"sqrt":      &tengo.GoFunction{Name: "sqrt", Value: FuncAFRF(math.Sqrt)},
	"tan":       &tengo.GoFunction{Name: "tan", Value: FuncAFRF(math.Tan)},
	"tanh":      &tengo.GoFunction{Name: "tanh", Value: FuncAFRF(math.Tanh)},
	"trunc":     &tengo.GoFunction{Name: "trunc", Value: FuncAFRF(math.Trunc)},
	"y0":        &tengo.GoFunction{Name: "y0", Value: FuncAFRF(math.Y0)},
	"y1":        &tengo.GoFunction{Name: "y1", Value: FuncAFRF(math.Y1)},
	"yn":        &tengo.GoFunction{Name: "yn", Value: FuncAIFRF(math.Yn)},
}
